name: Claude Code Review

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-review:
    if: |
      github.actor == github.repository_owner &&
      (
        (github.event_name == 'issue_comment' &&
         github.event.issue.pull_request &&
         contains(github.event.comment.body, '/claude review')) ||
        (github.event_name == 'pull_request_review_comment' &&
         contains(github.event.comment.body, '/claude review'))
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments on PRs
      issues: write # Required to post comments on issues
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}

            ユーザーがプルリクエストに `/claude review` とコメントしてコードレビューをリクエストしました。

            **重要な指示:**
            - すべてのレビューコメント、説明、フィードバックは日本語で記述してください
            - コード内のコメントも日本語で記述してください

            以下の観点からプルリクエストをレビューしてフィードバックを提供してください：
            - コード品質とベストプラクティス
            - 潜在的なバグや問題
            - パフォーマンスの考慮事項
            - セキュリティ上の懸念
            - テストカバレッジ

            リポジトリのCLAUDE.mdを参照して、スタイルと規約に関するガイダンスを確認してください。建設的で役立つフィードバックを心がけてください。

            手順：
            1. まず `gh pr view` を使用して現在のPRコンテキストを特定する
            2. PRの変更内容をレビューする
            3. `gh pr comment` または `gh issue comment` を使用してレビュー結果をコメントとして投稿する

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh issue comment:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

